webpack-contrib/worker-loader

- index.js
just added an if/else clause to prevent some crashes like this :
not sure if return a callback with null,null is the correct solution but works
```sh
10% 0/1 build modules
/Users/juju/Documents/projects/xxxxx/node_modules/worker-loader/index.js:39
var workerFile = entries[0].files[0];
^
TypeError: Cannot read property 'files' of undefined
```
> prevent crash when reloading dev server, fix #1

- index.js
For webpack 2 compatibility in watch/hot-reload mode.
> Explicitly mark worker-loader as non-cacheable.

- README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra
> Add -loader suffix to README examples to reflect Webpack 2 changes

- package.json
Currently, there's a peerdep warning when using worker-loader with webpack@2.2.0.
> "worker-loader@0.7.1" has incorrect peer dependency "webpack@>=0.9 <2 || ^2.1.0-beta"
As far as I can tell, it works just fine with the final release of webpack2. Are there any bugs I should fix first?
> Allow worker-loader to run with webpack@2.2.0

- README.md
This is to prevent someone from making the mistake I made, of specifying a `name` parameter and then breaking cacheability because the hash was excluded.
> Update docs to include adding hash to custom name

- README.md
For consistency with other loaders, see https://github.com/webpack-contrib/bundle-loader/pull/47
> docs(README): move usage link to header

- README.md
This adds the Typescript integration notes from https://github.com/webpack-contrib/worker-loader/issues/69 to the readme.
> Added Typescript integration to the readme

- index.js
- test/fixtures/nodejs-core-modules/entry.js
- test/fixtures/nodejs-core-modules/worker.js
- test/index.js
Should no longer throw errors for missing node modules, such as `fs`, `path` and etc.
It applies `NodeTargetPlugin` to child compiler if the main target uses `NodeTargetPlugin`. Every target apart from `webworker` and `web` use `NodeTargetPlugin`.
Fixes #44, #55
> feat: support loading node core modules

- .gitignore
- README.md
- index.js
- options.json
- test/fixtures/public-path-override/entry.js
- test/fixtures/public-path-override/worker.js
- test/index.js
Our web app hosts static assets on a CDN, making the loading of web worker scripts difficult due to cross-origin policies. The inline option works for most browsers, but we started experiencing some difficulties with Safari due to its handling of Unicode in blobs being inconsistent with other browsers. This proxy option lets the worker load from a same-origin URL; in our case, we have some middleware in which we proxy the request to the webpack dev server (for local development) or serve up a local file.
Added the ability to use a proxy URL when loading workers as a way to work around cross-origin policy issues.
> ℹ️  edited by @michael-ciniawsky (Formatting)
> feat: add `publicPath` support (`options.publicPath`)

- src/index.js
This functionality does 💯  not work with `webpack >= v2.0.0` anymore
ℹ️  Will be partially superseded by e.g https://github.com/webpack-contrib/worker-loader/issues/70#issuecomment-338846734
> refactor(index): remove legacy code (`webpack =< v1.0.0`)

- README.md
PrismJS only supports `typescript` not `ts` unfortunately. This resolves
some build warnings on the docs site and will allow the code block to be
properly highlighted.
> docs(README): fix syntax highlighting on `webpack.js.org`

- package.json
Cosmetic change: fixed the URL field in `package.json` (wrong copy-paste probably)
> fix(package): homepage URL typo

- README.md
README.md updated with instruction to remove hash from file name if needed.
> docs(README): add note about omitted hashes (`options.name`)

- src/index.js
`Tapable.apply` is deprecated in `tapable@1.0.0-x`.
The plugins should now call `apply` themselves.
Fixes #136
> refactor(index): remove `Tapable.apply` calls

- README.md
Updates the TypeScript example to use the ES6 import syntax like the other examples. Includes the change to `Worker.ts` mentioned in https://github.com/webpack-contrib/worker-loader/issues/111 to get it to work with `import` instead of `require`.
> Use ES6 import in TypeScript README example

- README.md
- src/options.json
- src/workers/InlineWorker.js
- src/workers/index.js
Allows worker-loader to create other worker types by adding an option `workerType` which defaults to `Worker` but could be used to create `ServiceWorker` or `SharedWorker`.
None
This is an updated version of #178
Signed-off-by: Andrew Thornton <art27@cantab.net>
> Add WorkerType functionality (replaces #178)

- src/workers/InlineWorker.js
- src/workers/index.js
fix memory leak
No
fixes #208
fixes #209
> fix: memory leak for inline workers

- src/options.json
- src/supportWebpack4.js
- src/supportWebpack5.js
- test/__snapshots__/esModule-option.test.js.snap
- test/__snapshots__/inline-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/name-options.test.js.snap
- test/__snapshots__/publicPath.test.js.snap
- test/__snapshots__/worker-option.test.js.snap
- test/esModule-option.test.js
- test/fixtures/basic/entry.js
- test/fixtures/query/entry.js
BREAKING CHANGE: switch on ES module syntax by default, use the `esModule` option if you need backward compatibility with Common JS modules
fixes #153
Yes, now we use ES module syntax by default
No
> feat: switch on ES module syntax

- src/index.js
- src/utils.js
- test/__snapshots__/chunkFilename-option.test.js.snap
- test/__snapshots__/filename-options.test.js.snap
- test/chunkFilename-option.test.js
- test/filename-options.test.js
BREAKING CHANGE: default value of the `filename` option based on `output.filename`
Better 0 CJS
Yes
Docs will be updated lately
> feat: default value of `filename` from `output.filename`

- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/external/entry.js
- test/fixtures/external/index.html
- test/fixtures/external/worker.js
- test/loader.test.js
> fix: respect `externals`

- package-lock.json
- package.json
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/publicPath.test.js.snap
- test/helpers/getResultFromBrowser.js
- test/publicPath.test.js
BREAKING CHANGE: the `publicPath` option default value based on `output.publicPath`
fixes #199
Yes
Docs will be updated lately, before stable release
> fix: respect `publicPath` from `output.publicPath`

- src/index.js
- test/__snapshots__/chunkFilename-option.test.js.snap
- test/__snapshots__/filename-options.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/fixtures/name/TypeDetection.js
- test/fixtures/name/entry.js
- test/fixtures/name/index.html
- test/helpers/getCompiler.js
- test/loader.test.js
> fix: interpolation `[name]` for the `filename` option

- src/supportWebpack4.js
- src/supportWebpack5.js
use cache API
Potential yes, only for webpack@5, but webpack@5 is beta so just update webpack@5 to latest beta
Hard to tests, tested manually, tests will be improve in future
> fix: compatibility with webpack@5 cache

- README.md
This missing escape character broke the options table making it seem like `fallback` was the default value for the `inline` option.
N/A
None
> docs(readme): add missing escape char in options table

- src/index.js
> fix: determine webpack peer dependency version

- src/supportWebpack5.js
This a fix for “Serializing big strings” warning with Webpack 5 filesystem cache
No
> fix: serializing big strings

- package.json
- src/runtime/inline.js
This change enables inline workers to be instantiated from worker scopes (where `window` isn't available.)
None.
fixes https://github.com/webpack-contrib/worker-loader/issues/306
> fix: make inline workers work from inside workers

- package-lock.json
- package.json
- test/helpers/compile.js
- test/helpers/getErrors.js
- test/helpers/getWarnings.js
- test/helpers/normalizeErrors.js
- test/publicPath.test.js
> chore(deps): update

- README.md
I found a simpler notation for TypeScript.
In this modification, the `worker-module!` prefix passed to `import` statement is not required anymore.
----
The `worker-module!` prefix originates from WebPack and which causes a compile error on non-WebPack systems.
This makes hard to test the code directly using testing frameworks such as Jest.
(Note: most testing frameworks only work with Node.js and do not support WebWorker. You should polyfill it using some utilities such as [https://github.com/astagi/workerloader-jest-transformer](workerloader-jest-transformer).)
TypeScript notation simplified.
cf: https://github.com/EllipticPIR/libepir/commit/f328396d85c5421f52ee623fb64a679e3687e457
> TypeScript: loading worker module more simply
