index.js

Allows specifying a name option in the worker loader query

Allow name option in loader query

---

README.md

Please check; I extracted the summary from quickly looking at the code.

docs(README): explain what the loader does

---

README.md

Add worker message example to README

---

README.md

Improve TypeScript integration example as per #94

---

src/index.js

fix(index): add `webpack >= v4.0.0` support

---

.circleci/config.yml
.editorconfig
.eslintrc.js
.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.jestrc
.prettierrc
README.md
codecov.yml
commitlint.config.js
package-lock.json
package.json
src/Error.js
src/index.js
src/workers/index.js
test/Errors.test.js
test/__snapshots__/Errors.test.js.snap
test/helpers/compiler.js
test/loader.test.js

This PR updates the repo to the latest `webpack-defaults`. Major improvements in tooling, github templates, and metadata.

refactor: webpack defaults

---

README.md

Few missing commas on your example code in README.md
You're awesome!

Update incorrect code examples on README.md

---

package-lock.json
package.json
src/index.js
src/supportWebpack4.js
src/supportWebpack5.js
src/supportWebpackPrior5.js
test/fixtures/inline-fallbacks/w1.js
test/fixtures/inline-fallbacks/w2.js
test/fixtures/inline-options/w1.js
test/fixtures/inline-options/w2.js
test/fixtures/inline-query/worker.js
test/fixtures/name-options/w1.js
test/fixtures/name-options/w2.js
test/fixtures/name-query/worker.js
test/fixtures/no-fallbacks/w1.js
test/fixtures/no-fallbacks/w2.js
test/fixtures/public-path-override/worker.js
test/fixtures/worker/worker.js
test/helpers/compiler.js
test/loader.test.js

Support webpack 5 (closes #223)
No
This PR blocks this [one](https://github.com/webpack/webpack/pull/9975)

refactor: support webpack 5

---

package-lock.json
package.json
test/__snapshots__/loader.test.js.snap
test/fixtures/puppeteer-1/entry.js
test/fixtures/puppeteer-1/index.html
test/fixtures/puppeteer-1/worker.js
test/helpers/compiler.js
test/helpers/getResultFromBrowser.js
test/helpers/index.js
test/loader.test.js

test: add test with puppeteer

---

package-lock.json
package.json
src/index.js
test/__snapshots__/loader.test.js.snap
test/fixtures/wasm/entry.js
test/loader.test.js

Better supporting webpack@5
No
No

fix: compatibility with webpack@5

---

setupTest.js
src/index.js
src/options.json
test/__snapshots__/chunkFilename-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/chunkFilename-option.test.js
test/fixtures/chunks/chunk.js
test/fixtures/chunks/entry.js
test/fixtures/chunks/index.html
test/fixtures/chunks/worker.js
test/helpers/getResultFromBrowser.js
test/loader.test.js

feat new `chunkFIlename` option
No
Docs will be updated lately

feat: the `chunkFilename` option

---

src/options.json
test/__snapshots__/chunkFilename-option.test.js.snap
test/__snapshots__/filename-options.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/__snapshots__/worker-option.test.js.snap
test/chunkFilename-option.test.js
test/filename-options.test.js
test/validate-options.test.js
test/worker-option.test.js

fix schema + tests
No, because we do not do release yet
No

test: refactor

---

src/supportWebpack4.js

use relative paths
No
hard to test

fix: cache identifier for webpack@4

---

src/index.js
src/supportWebpack4.js
src/supportWebpack5.js
src/utils.js

Fix unstable contenthash

---

src/index.js
src/supportWebpack4.js
src/supportWebpack5.js
src/utils.js

Refactor code

---

src/utils.js
test/__snapshots__/chunkFilename-option.test.js.snap
test/__snapshots__/esModule-option.test.js.snap
test/__snapshots__/filename-options.test.js.snap
test/__snapshots__/inline-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/publicPath.test.js.snap
test/__snapshots__/worker-option.test.js.snap
test/inline-option.test.js

refactor: use ES modules syntax for inline mode

---

test/__snapshots__/inline-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/publicPath.test.js.snap
test/inline-option.test.js
test/loader.test.js
test/publicPath.test.js

resolve todo in tests
No
worker-loader has fully compatibility with webpack@5 :star:

test: resolve todo

---

README.md
src/runtime/inline.js
test/__snapshots__/chunkFilename-option.test.js.snap
test/chunkFilename-option.test.js
test/filename-options.test.js
test/helpers/getCompiler.js
test/helpers/getResultFromBrowser.js
test/publicPath.test.js

add test for chunkFilename query parameters
No
No

Test chunkfilename query parameters

---

src/supportWebpack4.js
src/supportWebpack5.js
src/utils.js
test/__snapshots__/sourceMapperRegexp.test.js.snap
test/inline-option.test.js
test/sourceMapperRegexp.test.js

remove webpack sourceURL for  "devtool" option ("eval-source-map" value)
No
No

Fix: remove webpack sourceURL

---

README.md

I spent a bunch of time troubleshooting `Cannot read property 'version' of undefined` in my setup before coming across [this comment in Next.js's worker-loader example](https://github.com/vercel/next.js/blob/0ca24563be9658732eac158c31046ff58bfe78ca/test/integration/worker-loader/next.config.js#L2-L3). This is to save others that waste of time. :)
No breaking changes, just a small note in the README.
N/A

doc: be clear that this is webpack 4 specific

---

package-lock.json
package.json
src/index.js
src/options.json
test/__snapshots__/validate-options.test.js.snap

display links and descriptions on errors
no
no

feat: display links and descriptions on errors
